### ISSUE TITLE
tlslite/utils/cryptomath.py contains incorrect construct for Python 3

### ISSUE THREAD

**Issue by amsimms** [trevp/tlslite#119]
https://github.com/trevp/tlslite/blob/cd82fadb6bb958522b7457c5ed95890283437a4f/tlslite/utils/cryptomath.py#L121

The "ord()" function here is redundant with Python 3, and will produce an error.  It should be removed.

**Comment by tomato42** [comment]
tlslite is effectively abandoned, if you are interested in it, you can follow my fork of it: https://github.com/tomato42/tlslite-ng; that issue is already fixed there

**Comment by amsimms** [comment]
Yes, tlslite-ng works great.  Now I'm trying to get the conda folks to pick it up instead of tlslite.

**Comment by tomato42** [comment]
> Yes, tlslite-ng works great.

glad to hear that

> Now I'm trying to get the conda folks to pick it up instead of tlslite.

I most likely will have TLS 1.3 by the end of year, that should be enough of an argument :)
(technically, it already works, but it's not feature complete, and hasn't gone through enough testing for me to be confidant about that code)
not to mention smaller items like AES-GCM, or RSA-PSS support... see readme changelog for details (the 0.5.0 was the first release after the fork)

also, if you find any integration issues introduced by dropping in tlslite-ng in place of tlslite, I will consider those to be bugs (as in, I'm promising API compatibility with tlslite, but some older ciphers may be disabled by default in tlslite-ng while they worked out-of-the-box in tlslite, but I will not remove them ever, so ability to return to old functionality will be there)
