### ISSUE TITLE
s is not a string, but .find() is applied to it several times

### ISSUE THREAD

**Issue by amsimms** [trevp/tlslite#120]
https://github.com/trevp/tlslite/blob/cd82fadb6bb958522b7457c5ed95890283437a4f/tlslite/utils/openssl_rsakey.py#L102

s is not a string, in order to be searched with find() it needs to be converted, e.g.:

ss = str(s,'utf-8')

and then various searches become ss.find, ss.startswith, etc.

Line 106 is potentially problematic even with this fix:

s = s[start:]

since start is effectively a character count.

**Comment by tomato42** [comment]
it's the responsibility of the caller to provide `str` to the method, see [tls.py L134-140](https://github.com/tomato42/tlslite-ng/blob/3029e014231ffe34445d29300f0193a4be4b6ccd/scripts/tls.py#L134-L140)

**Comment by amsimms** [comment]
Unfortunately other code paths that end up calling this function insist on s being a byte oriented structure.  But as you say, tlslite-ng works great and resolves this issue completely.  Thanks for the response.
