### ISSUE TITLE
Continous Integration

### ISSUE THREAD

**Issue by tomato42** [trevp/tlslite#44]
Since tlslite has quite a few tests now and we want to preserve compatibility with both old and new Pythons, I think it would be good idea to have some Continuous Integration to run the tests against all those versions.

From what I found, travis-ci.org is free, integrates well with github and has support for multiple execution environments, including Python 2.6, 3.2 and later

**Comment by trevp** [comment]
Fine with me, if someone else does the work (e.g. give me yml file or whatever).

**Comment by tomato42** [comment]
you'll need to follow the instructions at http://docs.travis-ci.com/user/getting-started/
For the unittests to pass on 2.6 and 3.4 you'll need to merge pull #43

`.travis.yml` that should work is:
```
language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then travis_retry pip install unittest2; fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then unit2 discover; else python -m unittest discover; fi
  - ./setup.py install && make test

sudo: false
```

**Comment by trevp** [comment]
OK, maybe this is working.  And there's a python 2.6 problem, can you see that?

https://travis-ci.org/trevp/tlslite

**Comment by tomato42** [comment]
yes, I have access to it, I'll look into it

**Comment by tomato42** [comment]
And it looks like it works as advertised - the new push request was run in Travis and confirmed as fixed :)

**Comment by tomato42** [comment]
Since you mentioned that you want to preserve windows compatibility for the tests, you may be interested in adding CI with http://www.appveyor.com/ - they do Windows builds.

Unfortunately I have no experience using python on windows so I won't be able to help you with it...

**Comment by trevp** [comment]
Thanks, added an issue to keep track of it.

Trevor
