### ISSUE TITLE
Coverity measurement

### ISSUE THREAD

**Issue by tomato42** [trevp/tlslite#64]
So we now have pretty decent CI setup (thanks for the quick merges!), we can easily extend it to also include coverity checks.

Question is, how do we do it?

I see two options:
 - Coveralls, (example report: https://coveralls.io/r/pyca/pyopenssl )
 - diff-coverage test in `.travis.yml`, similar to the pylint check, where we just get pass/fail based on a threshold value

**Comment by trevp** [comment]
I'm not familiar with these, if you want to set something up I'm happy to commit it.

**Comment by tomato42** [comment]
Looks like adding it is relatively simple.

You'll need to:
 * merge #80
 * create account on https://coveralls.io (it uses github auth, so no need for new username/password)
 * add `tlslite` project to monitored ones
 * push the following change to `.travis.yml`:
```
after_success:
 - coveralls
```

That's all

**Comment by trevp** [comment]
alright I did that, we'll see what happens.

**Comment by tomato42** [comment]
Seems to be working: https://coveralls.io/r/trevp/tlslite
Thanks!
