### ISSUE TITLE
Website with tlslite is broken after some hours of operations

### ISSUE THREAD

**Issue by MirkoDziadzka** [trevp/tlslite#66]
# how to reproduce

Setup a web server with tlslite and SessionCache enabled

do the following request

```
$ openssl s_client -reconnect -connect 127.0.0.1:8082 < /dev/null
```

Wait for the session timeout (default is 4 hours)

Do the above request again.

# expected result

request should work

# actual result

The second request returns with an error on SSL level

```
89484:error:1409E0E5:SSL routines:SSL3_WRITE_BYTES:ssl handshake failure:/SourceCache/OpenSSL098/OpenSSL098-52.8.1/src/ssl/s3_pkt.c:564:
```

# analysis

explaination and proposed fix is in pull request https://github.com/trevp/tlslite/pull/67

**Comment by trevp** [comment]
That fix looks good except it's test is failing Python 3, when that gets corrected I'll integrate it.
