### ISSUE TITLE
Extended Master Secret support

### ISSUE THREAD

**Issue by tomato42** [trevp/tlslite#96]
Since `tlslite` supports session resumption and doesn't support ECDHE key exchange, it is vulnerable to the 3shake attack, as such, it should implement the [draft-ietf-tls-session-hash-04](https://tools.ietf.org/html/draft-ietf-tls-session-hash-04).

Lack of implicit full certificate verification makes this attack especially easy to perform against `tlslite`.

**Comment by trevp** [comment]
Doesn't triple-handshake attack require renegotiation by the client?  Which tlslite won't do?

**Comment by tomato42** [comment]
the draft does mention that resumption will work for that too

I may be reading it wrong though...

**Comment by trevp** [comment]
I think resumption and renegotiation are both used?
